name: tag
on:
  workflow_run:
    workflows:
    - test
    branches:
    - master
    types:
    - completed
jobs:
  tag:
    name: Tag the repository
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        PRERELEASE_SUFFIX: dev
        PRERELEASE: ${{ github.ref_name != 'master' }}
