name: test
on:
  push:
    branches:
    - master
  pull_request:
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.12" ]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install coveralls
        make install
    - name: Code formatting
      run: make code-format
    - name: Unit testing
      run: make unit-test
    - name: Integration testing
      run: make integration-test
    - name: Static Analysis
      run: make static-analysis
    - name: Security Analysis
      run: make security-analysis
    - name: Coveralls
      if: ${{ success() }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN}}
        COVERALLS_PARALLEL: true
      run: coveralls --service=github
  report:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v5
    - name: Coveralls Finish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN}}
      run: |
        python -m pip install --upgrade pip
        python -m pip install coveralls
        python -m coveralls --service=github --finish